services:
  - type: web
    name: event-management-system
    env: python
    buildCommand: |
      pip install -e .
      pip install -r ./requirements.txt
    startCommand: "gunicorn Event_Managment_System.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: DJANGO_SETTINGS_MODULE
        value: Event_Managment_System.Event_Managment_System.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
