# Generated by Django 5.2.4 on 2025-08-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_event_attendee_eventcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='organization_name',
            field=models.CharField(max_length=200),
        ),
    ]
