# Generated by Django 5.2.4 on 2025-08-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_organizer_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
